ex04 : ex04.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex05 : ex05.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex06 : ex06.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
	
ex07 : ex07.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
	
ex08 : ex08.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex09 : ex09.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex10 : ex10.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex11 : ex11.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image
