ex01 : ex01.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex02 : ex02.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex03 : ex03.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex04 : ex04.c sum.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex05 : ex05.c sum.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex06 : ex06.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex07 : ex07.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2