ex01 : ex01.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex02 : ex02.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex03 : ex03.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex04 : ex04.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image