ex01 : ex01.c ../engine/util.c ../engine/button.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2 
ex02 : ex02.c ../engine/util.c ../engine/button.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf