ex01 : ex01.c
	gcc -o $@ $^
ex02 : ex02.c
	gcc -o $@ $^
ex03 : ex03.c
	gcc -o $@ $^
ex04 : ex04.c
	gcc -o $@ $^
ex05 : ex05.c
	gcc -o $@ $^
ex06 : ex06.c
	gcc -o $@ $^
ex07 : ex07.c
	gcc -o $@ $^
ex08 : ex08.c
	gcc -o $@ $^
ex09 : ex09.c
	gcc -o $@ $^
ex10 : ex10.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2
ex11 : ex11.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2

