ex01 : ex01.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex04 : ex04.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex05 : ex05.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex06 : ex06.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex07 : ex07.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex07_cl : ex07.c
	cl /EHsc /MD $< /Fo../out/$@.obj /Fe../out/$@.exe 
ex08 : ex08.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex09 : ex09.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex10 : ex10.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2

ex11 : ex11.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex12 : ex12.c
	gcc -Wall -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
