ex01 : ex01.c ../engine/graph.c
	gcc -g -o ../out/$@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

ex02 : ex02.c ../engine/graph.c ../engine/core.c ../engine/entity/sprite.c
	gcc -g -o ../out/$@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf