game:
	gcc main.c -o out/play -I /usr/local/include/SDL2 -L /usr/local/lib -l SDL2 -D_THREAD_SAFE -I/usr/local/include/SDL2 -L/usr/local/lib -lSDL2_image -lSDL2
win:
	gcc main.c -o out/play.exe -D_THREAD_SAFE -I C:\Users\User\Desktop\mywork\libs\sdl2\include  -L C:\Users\User\Desktop\mywork\libs\sdl2\lib  -lSDL2_image -lSDL2